name: "Housekeeping"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/housekeeping.yaml"
  schedule:
  - cron: "0 1 * * *"

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    name: "Housekeeping"
    steps:
      - name: Checkout branch
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Containers - Fetch new application versions
        run: |
          find ./apps -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | while read app; do
            if test -f "./apps/${app}/latest-version.sh"; then
              version=$(bash "./apps/${app}/latest-version.sh")
              if [[ ! -z "${version}" || "${version}" != "null" ]]; then
                echo "${version}" | tee "./apps/${app}/VERSION" > /dev/null
                echo "App: ${app} using version: ${version}"
              fi
            fi
            if test -f "./apps/${app}/BASE"; then
              if test -f "./apps/${app}/latest-base.sh"; then
                base=$(bash "./apps/${app}/latest-base.sh")
                if [[ ! -z "${base}" || "${base}" != "null" ]]; then
                  echo "${base}" | tee "apps/${app}/BASE" > /dev/null
                  echo "App: ${app} using Base: ${base}"
                fi
              fi
            fi
          done
      - name: Containers - Fetch new base versions
        run: |
          find ./base -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | while read app; do
            if test -f "./base/${app}/latest-version.sh"; then
              version=$(bash "./base/${app}/latest-version.sh")
              if [[ ! -z "${version}" || "${version}" != "null" ]]; then
                echo "${version}" | tee "./base/${app}/VERSION" > /dev/null
                echo "${app} ${version}"
              fi
            fi
          done

      - name: Commit and Push Housekeeping
        run: |
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          git add --all
          git commit -sm "Daily Housekeeping" || exit 0
          git push
